import http from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { VERSION } from './domain.js';
import { initStore,listAgents,getAgent,createAgent,updateAgent,listTasks,getTask,createTask,matches,selectProvider,acceptTask,startTask,deliverTask,reviseTask,completeTask,disputeTask,cancelTask,listMessages,createMessage,stats,launchKpis,metrics,recentEvents,recordMetric,getIdempotent,saveIdempotent,issueCredential,authenticateApiKey,listCredentials,revokeCredential,rotateCredential,createVerificationChallenge,getVerificationChallenge,completeVerificationChallenge,listPayments,getPayment,getTaskPayment,createPayment,transitionPayment,paymentStats } from './store.js';
import { agentCard, openApi, handleMcp, handleA2A } from './protocols.js';
import { robotsTxt, sitemapXml, llmsTxt, llmsFullTxt, securityTxt, mcpServerJson, webManifest } from './discovery.js';
import { enforceRateLimit,idempotencyKey,requestFingerprint,requestSource,bearerToken,verifyOwnershipUrl } from './security.js';
import { PLATFORM_FEE_BPS, paymentQuote } from './payments.js';

await initStore();
const port=Number(process.env.PORT||8787),publicDir=fileURLToPath(new URL('../public/',import.meta.url));
const server=http.createServer(async(req,res)=>{try{
  const url=new URL(req.url,`http://${req.headers.host||'localhost'}`),origin=`${url.protocol}//${url.host}`,source=requestSource(req,url);
  if(req.method==='OPTIONS')return send(res,204,null);
  enforceRateLimit(req,url.pathname.startsWith('/api/')?'api':'public');
  if(req.method==='GET'&&url.pathname==='/health')return send(res,200,{status:'ok',service:'taskbay',version:VERSION});
  if(req.method==='GET'&&(url.pathname==='/.well-known/agent.json'||url.pathname==='/.well-known/agent-card.json')){await recordMetric('discovery.agent_card',{source,audit:false});return send(res,200,agentCard(origin));}
  if(req.method==='GET'&&url.pathname==='/openapi.json'){await recordMetric('discovery.openapi',{source,audit:false});return send(res,200,openApi(origin));}
  if(req.method==='GET'&&url.pathname==='/server.json')return send(res,200,mcpServerJson(origin));
  if(req.method==='GET'&&url.pathname==='/robots.txt')return textResponse(res,200,robotsTxt(origin),'text/plain; charset=utf-8');
  if(req.method==='GET'&&url.pathname==='/sitemap.xml')return textResponse(res,200,sitemapXml(origin),'application/xml; charset=utf-8');
  if(req.method==='GET'&&url.pathname==='/llms.txt')return textResponse(res,200,llmsTxt(origin),'text/plain; charset=utf-8');
  if(req.method==='GET'&&url.pathname==='/llms-full.txt')return textResponse(res,200,llmsFullTxt(origin),'text/plain; charset=utf-8');
  if(req.method==='GET'&&url.pathname==='/.well-known/security.txt')return textResponse(res,200,securityTxt(origin),'text/plain; charset=utf-8');
  if(req.method==='GET'&&url.pathname==='/manifest.webmanifest')return send(res,200,webManifest(origin),{'content-type':'application/manifest+json; charset=utf-8','cache-control':'public, max-age=3600'});
  if(url.pathname==='/mcp'&&req.method==='GET')return send(res,405,{error:'method_not_allowed'},{allow:'POST'});
  if(req.method==='POST'&&url.pathname==='/mcp'){validateMcpOrigin(req,origin);await recordMetric('protocol.mcp_call',{source,audit:false});return await bridge(res,await handleMcp(toRequest(req,origin,url),{source}));}
  if(req.method==='POST'&&url.pathname==='/a2a'){await recordMetric('protocol.a2a_call',{source,audit:false});return await bridge(res,await handleA2A(toRequest(req,origin,url),{source}));}
  if(req.method==='GET'&&url.pathname==='/api/v1/stats')return send(res,200,stats());
  if(req.method==='GET'&&url.pathname==='/api/v1/kpis')return send(res,200,launchKpis());
  if(req.method==='GET'&&url.pathname==='/api/v1/metrics')return send(res,200,metrics());
  if(req.method==='GET'&&url.pathname==='/api/v1/events')return send(res,200,{events:publicEvents(recentEvents(Number(url.searchParams.get('limit')||30)))});
  if(req.method==='GET'&&url.pathname==='/api/v1/payments/config')return send(res,200,{provider:process.env.TASKBAY_PAYMENT_PROVIDER||process.env.RELAYMARKET_PAYMENT_PROVIDER||'mock',live:false,platformFeeBps:PLATFORM_FEE_BPS,platformFeePercent:PLATFORM_FEE_BPS/100,feeRounding:'floor_minor_unit',processorFeesIncluded:false,releaseModel:'after_task_completion',note:'Mock provider is for development only; production payment capture remains disabled until a real provider is configured.'});
  if(req.method==='GET'&&url.pathname==='/api/v1/payments/quote'){try{return send(res,200,{quote:paymentQuote(Number(url.searchParams.get('amountMinor')),url.searchParams.get('currency')||'USD')});}catch(e){return send(res,e.status||400,{error:e.code||'invalid_payment_quote',message:e.message});}}
  if(req.method==='GET'&&url.pathname==='/api/v1/payments/stats')return send(res,200,paymentStats());

  if(req.method==='GET'&&url.pathname==='/api/v1/agents'){await recordMetric('agent.discovery',{source,audit:false});return send(res,200,{agents:listAgents({capability:url.searchParams.get('capability'),protocol:url.searchParams.get('protocol'),available:url.searchParams.get('available')})});}
  if(req.method==='POST'&&url.pathname==='/api/v1/agents')return await mutation(req,res,url,source,async b=>{const agent=await createAgent(b,{source}),credential=await issueCredential(agent.id,{source});return{status:201,payload:{agent,credential:{apiKey:credential.apiKey,credentialId:credential.credentialId,warning:'Store this API key securely; it is returned only through this registration response.'}}}});
  const am=url.pathname.match(/^\/api\/v1\/agents\/([^/]+)$/);if(am){const agentId=decodeURIComponent(am[1]);if(req.method==='GET'){await recordMetric('agent.viewed',{source,audit:false});const a=getAgent(agentId);return a?send(res,200,{agent:a}):send(res,404,{error:'agent_not_found'});}if(req.method==='PATCH')return await mutation(req,res,url,source,async b=>{await requireAgent(req,agentId);return{status:200,payload:{agent:await updateAgent(agentId,b,{source})}}});}
  const cm=url.pathname.match(/^\/api\/v1\/agents\/([^/]+)\/credentials(?:\/([^/]+)\/(rotate|revoke))?$/);if(cm){const agentId=decodeURIComponent(cm[1]),credentialId=cm[2]?decodeURIComponent(cm[2]):null,action=cm[3]||null;await requireAgent(req,agentId);if(req.method==='GET'&&!credentialId)return send(res,200,{credentials:listCredentials(agentId)});if(req.method==='POST'&&credentialId&&action==='rotate')return await mutation(req,res,url,source,async()=>{const credential=await rotateCredential(agentId,credentialId,{source});return{status:201,payload:{credential:{apiKey:credential.apiKey,credentialId:credential.credentialId,warning:'Store this API key securely; the previous credential is now revoked.'}}}});if(req.method==='POST'&&credentialId&&action==='revoke')return await mutation(req,res,url,source,async()=>({status:200,payload:{credential:await revokeCredential(agentId,credentialId,{source})}}));return send(res,405,{error:'method_not_allowed'});}
  const vm=url.pathname.match(/^\/api\/v1\/agents\/([^/]+)\/verification-challenges(?:\/([^/]+)\/verify)?$/);if(vm){const agentId=decodeURIComponent(vm[1]),challengeId=vm[2]?decodeURIComponent(vm[2]):null;await requireAgent(req,agentId);if(req.method==='POST'&&!challengeId)return await mutation(req,res,url,source,async b=>({status:201,payload:{challenge:await createVerificationChallenge(agentId,b.endpointIndex??0,source)}}));if(req.method==='POST'&&challengeId)return await mutation(req,res,url,source,async()=>{const challenge=getVerificationChallenge(agentId,challengeId);if(!challenge)throw Object.assign(new Error('Verification challenge not found'),{status:404,code:'verification_challenge_not_found'});await verifyOwnershipUrl(challenge.verificationUrl,challenge.token);return{status:200,payload:{agent:await completeVerificationChallenge(agentId,challengeId,source),verifiedEndpoint:challenge.endpointUrl}}});}
  if(req.method==='GET'&&url.pathname==='/api/v1/tasks'){await recordMetric('task.discovery',{source,audit:false});return send(res,200,{tasks:listTasks(url.searchParams.get('status')||'all')});}
  if(req.method==='POST'&&url.pathname==='/api/v1/tasks')return await mutation(req,res,url,source,async b=>{if(b.requesterAgentId)await requireAgent(req,b.requesterAgentId);return{status:201,payload:{task:await createTask(b,{source})}}});
  const pm=url.pathname.match(/^\/api\/v1\/tasks\/([^/]+)\/payment$/);if(pm){const taskId=decodeURIComponent(pm[1]);if(req.method==='GET'){const payment=getTaskPayment(taskId);if(!payment)return send(res,404,{error:'payment_not_found'});await requireAgent(req,payment.requesterAgentId);return send(res,200,{payment});}if(req.method==='POST')return await mutation(req,res,url,source,async b=>{await requireAgent(req,b.requesterAgentId);return{status:201,payload:{payment:await createPayment(taskId,b.requesterAgentId,b,{source})}}});}
  const paym=url.pathname.match(/^\/api\/v1\/payments\/([^/]+)(?:\/mock\/(fund|hold|release|refund|fail|cancel))?$/);if(paym){const paymentId=decodeURIComponent(paym[1]),action=paym[2]||null;if(!action&&req.method==='GET'){const payment=getPayment(paymentId);if(!payment)return send(res,404,{error:'payment_not_found'});await requireAgent(req,payment.requesterAgentId);return send(res,200,{payment});}if(req.method==='POST'&&action){if((process.env.TASKBAY_PAYMENT_PROVIDER||process.env.RELAYMARKET_PAYMENT_PROVIDER||'mock')!=='mock')return send(res,404,{error:'not_found'});const map={fund:'funded',hold:'held',release:'released',refund:'refunded',fail:'failed',cancel:'cancelled'};return await mutation(req,res,url,source,async b=>{const payment=getPayment(paymentId);if(!payment)throw Object.assign(new Error('Payment not found'),{status:404,code:'payment_not_found'});await requireAgent(req,b.actorAgentId||payment.requesterAgentId);return{status:200,payload:{payment:await transitionPayment(paymentId,map[action],b.actorAgentId||payment.requesterAgentId,b,{source})}}});}}

  const mm=url.pathname.match(/^\/api\/v1\/tasks\/([^/]+)\/messages$/);if(mm){const taskId=decodeURIComponent(mm[1]);if(req.method==='GET'){await requireTaskParticipant(req,taskId);return send(res,200,{messages:listMessages(taskId)});}if(req.method==='POST')return await mutation(req,res,url,source,async b=>{await requireAgent(req,b.fromAgentId);return{status:201,payload:{message:await createMessage(taskId,b,{source})}}});}
  const tm=url.pathname.match(/^\/api\/v1\/tasks\/([^/]+)(?:\/(matches|select|accept|start|deliver|revise|complete|dispute|cancel))?$/);if(tm){const taskId=decodeURIComponent(tm[1]),action=tm[2];if(!action&&req.method==='GET'){await recordMetric('task.viewed',{source,audit:false});const t=getTask(taskId);return t?send(res,200,{task:t}):send(res,404,{error:'task_not_found'});}if(action==='matches'&&req.method==='GET'){await recordMetric('task.match_requested',{source,audit:false});return send(res,200,{matches:matches(taskId)});}if(req.method!=='POST')return send(res,405,{error:'method_not_allowed'});return await mutation(req,res,url,source,async b=>{if(action==='select'){await requireAgent(req,b.requesterAgentId);return{status:200,payload:{task:await selectProvider(taskId,b.requesterAgentId,b.providerAgentId,{source})}}}if(action==='accept'){await requireAgent(req,b.providerAgentId);return{status:200,payload:{task:await acceptTask(taskId,b.providerAgentId,{source})}}}if(action==='start'){await requireAgent(req,b.providerAgentId);return{status:200,payload:{task:await startTask(taskId,b.providerAgentId,{source})}}}if(action==='deliver'){await requireAgent(req,b.providerAgentId);return{status:200,payload:{task:await deliverTask(taskId,b.providerAgentId,b,{source})}}}if(action==='revise'){await requireAgent(req,b.requesterAgentId);return{status:200,payload:{task:await reviseTask(taskId,b.requesterAgentId,b,{source})}}}if(action==='complete'){await requireAgent(req,b.requesterAgentId);return{status:200,payload:{task:await completeTask(taskId,b.requesterAgentId,b,{source})}}}if(action==='dispute'){await requireAgent(req,b.requesterAgentId);return{status:200,payload:{task:await disputeTask(taskId,b.requesterAgentId,b,{source})}}}if(action==='cancel'){await requireAgent(req,b.actorAgentId);return{status:200,payload:{task:await cancelTask(taskId,b.actorAgentId,{source})}}}throw Object.assign(new Error('Unknown action'),{status:404,code:'not_found'});});}
  if(req.method==='GET')return staticFile(res,url.pathname,origin);return send(res,404,{error:'not_found'});
}catch(e){if(e.retryAfter)res.setHeader('retry-after',String(e.retryAfter));return send(res,e.status||500,{error:e.code||'internal_error',message:e.message})}});
server.listen(port,()=>console.log(`TaskBay ${VERSION} listening on http://localhost:${port}`));

async function requireTaskParticipant(req,taskId){const t=getTask(taskId);if(!t)throw Object.assign(new Error('Task not found'),{status:404,code:'task_not_found'});const actor=await authenticateApiKey(bearerToken(req));if(!actor)throw Object.assign(new Error('Valid agent API key required'),{status:401,code:'invalid_agent_api_key'});if(![t.requesterAgentId,t.providerAgentId].filter(Boolean).includes(actor))throw Object.assign(new Error('Actor is not a task participant'),{status:403,code:'actor_not_authorized'});return actor}
function publicEvents(events=[]){return events.map(e=>({type:e.type,source:e.detail?.source||'direct',at:e.at}))}
async function requireAgent(req,agentId){if(!agentId)throw Object.assign(new Error('Agent identity required'),{status:401,code:'agent_identity_required'});const authenticated=await authenticateApiKey(bearerToken(req));if(!authenticated)throw Object.assign(new Error('Valid agent API key required'),{status:401,code:'invalid_agent_api_key'});if(authenticated!==agentId)throw Object.assign(new Error('API key does not belong to claimed agent'),{status:403,code:'agent_identity_mismatch'});return authenticated}
async function mutation(req,res,url,source,fn){const b=await body(req),key=idempotencyKey(req),scope=`${req.method}:${url.pathname}`,hash=requestFingerprint(req.method,url.pathname,b);if(key){const cached=await getIdempotent(scope,key,hash);if(cached)return send(res,cached.status,cached.payload,{'x-idempotent-replay':'true'});}const out=await fn(b);if(key)await saveIdempotent(scope,key,hash,out);return send(res,out.status,out.payload)}
async function body(req){const chunks=[];let total=0;for await(const c of req){total+=c.length;if(total>1_000_000)throw Object.assign(new Error('Request too large'),{status:413,code:'request_too_large'});chunks.push(c)}if(!chunks.length)return{};try{return JSON.parse(Buffer.concat(chunks).toString('utf8'))}catch{throw Object.assign(new Error('Invalid JSON'),{status:400,code:'invalid_json'})}}
function send(res,status,payload,extra={}){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'no-referrer','x-frame-options':'DENY','permissions-policy':'camera=(), microphone=(), geolocation=(), payment=(), usb=()','cross-origin-opener-policy':'same-origin',...extra});res.end(payload===null?'':JSON.stringify(payload))}
function textResponse(res,status,payload,type){res.writeHead(status,{'content-type':type,'cache-control':'public, max-age=300','x-content-type-options':'nosniff'});res.end(payload)}
function validateMcpOrigin(req,origin){const presented=req.headers.origin;if(presented&&presented!==origin)throw Object.assign(new Error('MCP Origin header does not match this server'),{status:403,code:'invalid_mcp_origin'})}
async function staticFile(res,path,origin){const relative=path==='/'?'index.html':path.replace(/^\//,'');if(relative.includes('..'))return send(res,400,{error:'bad_path'});try{const file=join(publicDir,relative),ext=extname(file),types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml','.png':'image/png'};let data=await readFile(file);if(ext==='.html'){data=data.toString('utf8').replaceAll('__PUBLIC_ORIGIN__',origin).replaceAll('__GOOGLE_SITE_VERIFICATION__',String(process.env.GOOGLE_SITE_VERIFICATION||''));}res.writeHead(200,{'content-type':types[ext]||'application/octet-stream','cache-control':'no-cache','x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'no-referrer','permissions-policy':'camera=(), microphone=(), geolocation=(), payment=(), usb=()',...(ext==='.html'?{'content-security-policy':`default-src 'self'; base-uri 'none'; object-src 'none'; frame-ancestors 'none'; form-action 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; font-src 'self'`}:{})});res.end(data)}catch{return send(res,404,{error:'not_found'})}}
function toRequest(req,origin,url){return new Request(`${origin}${url.pathname}`,{method:req.method,headers:req.headers,body:ReadableStream.from(req),duplex:'half'})}
async function bridge(res,response){const h=Object.fromEntries(response.headers.entries());delete h['access-control-allow-origin'];res.writeHead(response.status,h);res.end(Buffer.from(await response.arrayBuffer()))}
